export const GET_LOCATION_LIST = "GET_LOCATION_LIST";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const GET_LOCATION_DETAIL = "GET_LOCATION_DETAIL";
export const RESET_LOCATION_DETAIL = "RESET_LOCATION_DETAIL";

export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";
export const RESET_COUNTRY_LIST = "RESET_COUNTRY_LIST";
