export const GET_USERS_LIST = "GET_USERS_LIST";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const DELETE_USER = "DELETE_USER";
export const GET_USER_LIST_LOADING = "GET_USER_LIST_LOADING" 
export const GET_USER_DOCUMENTS_LIST = "GET_USER_DOCUMENTS_LIST"
export const GET_USER_DOCUMENTS_ISLOADING = "GET_USER_DOCUMENTS_ISLOADING"