export const GET_ALL_INVOICES = "GET_ALL_INVOICES";
export const GET_SINGLE_INVOICE_DETAIL = "GET_SINGLE_INVOICE_DETAIL"
export const GET_ALL_INVOICES_IS_LOADING = "GET_ALL_INVOICES_IS_LOADING" 
export const GET_WORK_ORDER_FOR_INVOICE = "GET_WORK_ORDER_FOR_INVOICE"