export const GET_ALL_PURCHASE = "GET_ALL_PURCHASE"
export const GET_ALL_PURCHASE_ISLOADING = "GET_ALL_PURCHASE_ISLOADING"
export const GET_SINGLE_PURCHASE_DETAIL = "GET_SINGLE_PURCHASE_DETAIL"
export const GET_PO_NUMBER = "GET_PO_NUMBER" 